# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
                ('is_course_lab', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_1', models.IntegerField()),
                ('mcq_2', models.IntegerField()),
                ('mcq_3', models.IntegerField()),
                ('textual_question_1', models.CharField(max_length=500)),
                ('textual_question_2', models.CharField(max_length=500)),
                ('feedback_given_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Theory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_1', models.IntegerField()),
                ('mcq_2', models.IntegerField()),
                ('mcq_3', models.IntegerField()),
                ('textual_question_1', models.CharField(max_length=500)),
                ('textual_question_2', models.CharField(max_length=500)),
                ('feedback_given_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dean_or_director', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_view_superview', 'can view superview'), ('can_view_normalview', 'can view normalview')),
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dean_or_director', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor_And_Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='professor_and_students',
            name='students',
            field=models.ManyToManyField(to='portal.Student'),
        ),
        migrations.AddField(
            model_name='feedback_theory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Professor_And_Students'),
        ),
        migrations.AddField(
            model_name='feedback_theory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback_lab',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Professor_And_Students'),
        ),
        migrations.AddField(
            model_name='course',
            name='assigned_to_professor',
            field=models.ManyToManyField(to='portal.Professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='students_of_course',
            field=models.ManyToManyField(to='portal.Student'),
        ),
    ]
