# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='dean_or_director',
            field=models.BooleanField(default=True),
        ),
    ]
