# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='professor',
            name='linkz',
        ),
        migrations.AddField(
            model_name='course',
            name='assigned_to',
            field=models.ManyToManyField(to='portal.Professor'),
        ),
        migrations.AddField(
            model_name='professor',
            name='teaching',
            field=models.ManyToManyField(to='portal.Course'),
        ),
    ]
