# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20170705_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='assigned_to',
            new_name='assigned_to_professor',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='teaching',
        ),
        migrations.AddField(
            model_name='course',
            name='students_of_course',
            field=models.ManyToManyField(to='portal.Student'),
        ),
    ]
