# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170712_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_lab',
            name='textual_question_2',
            field=models.CharField(max_length=600),
        ),
    ]
