# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170705_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor_And_Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Professor')),
                ('students', models.ManyToManyField(to='portal.Student')),
            ],
        ),
    ]
