# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_professor_and_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Theory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_1', models.IntegerField()),
                ('mcq_2', models.IntegerField()),
                ('mcq_3', models.IntegerField()),
                ('textual_question_1', models.CharField(max_length=500)),
                ('textual_question_2', models.CharField(max_length=500)),
                ('feedback_given_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Professor_And_Students')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='is_course_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professor',
            name='dean_or_director',
            field=models.BooleanField(default=False),
        ),
    ]
