# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 14:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0005_auto_20170705_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_1', models.IntegerField()),
                ('mcq_2', models.IntegerField()),
                ('mcq_3', models.IntegerField()),
                ('textual_question_1', models.CharField(max_length=500)),
                ('textual_question_2', models.CharField(max_length=500)),
                ('feedback_given_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Professor_And_Students')),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dean_or_director', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_view_superview', 'can view superview'), ('can_view_normalview', 'can view normalview')),
            },
        ),
    ]
